# Generated by Django 4.2.14 on 2025-05-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
