# Generated by Django 4.2.14 on 2024-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_company_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.CharField(default="", max_length=255),
        ),
    ]
