# Generated by Django 4.2.14 on 2024-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.TextField(default=""),
        ),
    ]
