# Generated by Django 4.2.14 on 2024-08-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_order_completed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
