# Generated by Django 4.2.14 on 2024-08-16 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0007_usercompany_remove_company_user_userrole_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="users",
        ),
        migrations.AddField(
            model_name="usercompany",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="order.company",
            ),
        ),
        migrations.AddField(
            model_name="usercompany",
            name="role",
            field=models.CharField(
                choices=[("STORE", "Store"), ("ADMIN", "Admin")],
                default="STORE",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="usercompany",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
