# Generated by Django 4.2.14 on 2024-08-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_company_users_usercompany_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='has_delivery',
        ),
    ]
