# Generated by Django 4.2.14 on 2024-09-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_order_has_topper"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercompany",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
