# Generated by Django 4.2.14 on 2024-09-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_usercompany_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
